# Generated by Django 4.2.3 on 2023-07-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
